// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmAsP4oPkaH4WC7xZLnbKOPbSXFXZdfA4',
    appId: '1:822727262248:web:b2396319da0090cc40b51d',
    messagingSenderId: '822727262248',
    projectId: 'stemious-hands-on-task',
    authDomain: 'stemious-hands-on-task.firebaseapp.com',
    storageBucket: 'stemious-hands-on-task.appspot.com',
    measurementId: 'G-FTEBYMEZ4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_ouG83SCUuFRVVVCy0YLTtIJAICUZyU',
    appId: '1:822727262248:android:e0fc75bf387946f740b51d',
    messagingSenderId: '822727262248',
    projectId: 'stemious-hands-on-task',
    storageBucket: 'stemious-hands-on-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhejxx7kwUxM1HfqFyPNIqd33bQNhlGU8',
    appId: '1:822727262248:ios:0048aeffacbf344040b51d',
    messagingSenderId: '822727262248',
    projectId: 'stemious-hands-on-task',
    storageBucket: 'stemious-hands-on-task.appspot.com',
    iosBundleId: 'com.example.personalBudgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhejxx7kwUxM1HfqFyPNIqd33bQNhlGU8',
    appId: '1:822727262248:ios:0048aeffacbf344040b51d',
    messagingSenderId: '822727262248',
    projectId: 'stemious-hands-on-task',
    storageBucket: 'stemious-hands-on-task.appspot.com',
    iosBundleId: 'com.example.personalBudgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmAsP4oPkaH4WC7xZLnbKOPbSXFXZdfA4',
    appId: '1:822727262248:web:c665d0e9ddd7f46840b51d',
    messagingSenderId: '822727262248',
    projectId: 'stemious-hands-on-task',
    authDomain: 'stemious-hands-on-task.firebaseapp.com',
    storageBucket: 'stemious-hands-on-task.appspot.com',
    measurementId: 'G-W9N9DCM12R',
  );
}
